//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Areas.admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ayarlar
    {
        public int id { get; set; }
        public string site_adi { get; set; }
        public string title { get; set; }
        public string keywords { get; set; }
        public string description { get; set; }
        public string adres { get; set; }
        public string sehir { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string hakkimizda { get; set; }
        public string iletisim { get; set; }
        public string nasil_calisir { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public string instagram { get; set; }
    }
}
