//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Areas.admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projeEntities1 : DbContext
    {
        public projeEntities1()
            : base("name=projeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ayarlar> ayarlar { get; set; }
        public virtual DbSet<bakiye_yukle> bakiye_yukle { get; set; }
        public virtual DbSet<engellenen_uyeler> engellenen_uyeler { get; set; }
        public virtual DbSet<galeriler> galeriler { get; set; }
        public virtual DbSet<itetisim_mesajlari> itetisim_mesajlari { get; set; }
        public virtual DbSet<kargolar> kargolar { get; set; }
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<mesajlasmalar> mesajlasmalar { get; set; }
        public virtual DbSet<slider> slider { get; set; }
        public virtual DbSet<teklif_butonlari> teklif_butonlari { get; set; }
        public virtual DbSet<teklif_miktarlari> teklif_miktarlari { get; set; }
        public virtual DbSet<teklifler> teklifler { get; set; }
        public virtual DbSet<urun_teklif_butonlari> urun_teklif_butonlari { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<uyeler> uyeler { get; set; }
        public virtual DbSet<zamanlar> zamanlar { get; set; }
    }
}
