//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Areas.admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunler()
        {
            this.galeriler = new HashSet<galeriler>();
            this.kargolar = new HashSet<kargolar>();
            this.teklif_miktarlari = new HashSet<teklif_miktarlari>();
            this.teklifler = new HashSet<teklifler>();
            this.urun_teklif_butonlari = new HashSet<urun_teklif_butonlari>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
        public string resim { get; set; }
        public int stok { get; set; }
        public string aciklama { get; set; }
        public decimal taban_fiyati { get; set; }
        public decimal tavan_fiyati { get; set; }
        public Nullable<System.DateTime> baslangic_tarihi { get; set; }
        public Nullable<System.DateTime> bitis_tarihi { get; set; }
        public string durum { get; set; }
        public string description { get; set; }
        public string keywords { get; set; }
        public int uye_id { get; set; }
        public int kategori_id { get; set; }
        public System.DateTime tarih { get; set; }
        public string yayin_durumu { get; set; }
        public string teklif_durumu { get; set; }
        public string onay_durumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<galeriler> galeriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kargolar> kargolar { get; set; }
        public virtual kategoriler kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teklif_miktarlari> teklif_miktarlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teklifler> teklifler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<urun_teklif_butonlari> urun_teklif_butonlari { get; set; }
        public virtual uyeler uyeler { get; set; }
    }
}
