//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Areas.admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zamanlar
    {
        public int id { get; set; }
        public string tur { get; set; }
        public string zaman_dilimi { get; set; }
        public string zaman { get; set; }
    }
}
